image: Visual Studio 2017

skip_branch_with_pr: true

environment:
  VERSION: 4.0.0

cache:
  - tools -> build.ps1

build_script: 
  - ps: .\build.ps1

test: off

artifacts:
  - path: 'src\**\*.nupkg'